# Generated by Django 5.2.17 on 2026-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_message', models.TextField()),
                ('assistant_response', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Interaction',
                'verbose_name_plural': 'Chat Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(help_text='Unique identifier e.g. profile_summary, edu_degree', max_length=100, unique=True)),
                ('category', models.CharField(db_index=True, help_text='e.g. Profile, Education, Experience, Skills, Projects, Certifications, Contact', max_length=100)),
                ('title', models.CharField(help_text='Brief headline for the chunk', max_length=255)),
                ('content', models.TextField(help_text="The verified factual information grounded in Daniel's resume")),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector embedding list of floats')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Knowledge Chunk',
                'verbose_name_plural': 'Resume Knowledge Chunks',
                'ordering': ['category', 'title'],
            },
        ),
    ]
