# Generated by Django 5.2.15 on 2026-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=50)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, default='/static/images/certificate-placeholder.svg', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=250)),
                ('score', models.CharField(help_text='e.g. 8.2 CGPA or 85%', max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education Records',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, default='India', max_length=150)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.CharField(help_text='e.g. Nov 2024 or 2024', max_length=50)),
                ('end_date', models.CharField(blank=True, default='Present', help_text='e.g. Present or Dec 2024', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('responsibilities_raw', models.TextField(blank=True, help_text='Bullet points or newline/comma separated responsibilities')),
                ('tech_stack', models.CharField(blank=True, help_text='e.g. Python, Flask, Angular, PostgreSQL', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Daniel John Britto', max_length=150)),
                ('title', models.CharField(default='Python Backend Developer | Django & Flask Developer', max_length=255)),
                ('headline', models.CharField(default='Passionate Backend Developer specializing in scalable Python web applications and API integration.', max_length=255)),
                ('bio', models.TextField(default='I am a dedicated Python Backend Developer with hands-on experience building robust APIs, web applications, and database architectures. Proficient in Django, Flask, PostgreSQL, MySQL, and modern backend practices.')),
                ('years_of_experience', models.PositiveIntegerField(default=1)),
                ('projects_completed', models.PositiveIntegerField(default=8)),
                ('location', models.CharField(default='India', max_length=150)),
                ('email', models.EmailField(default='danieljohnbritto@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=30)),
                ('resume_url', models.CharField(blank=True, default='#', max_length=500)),
                ('profile_image_url', models.CharField(blank=True, default='/static/images/profile.svg', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, default='/static/images/project-placeholder.svg', max_length=500)),
                ('tech_stack', models.CharField(help_text='Comma-separated e.g. Python, Django, PostgreSQL', max_length=255)),
                ('features_raw', models.TextField(blank=True, help_text='Newline separated key features')),
                ('github_url', models.URLField(blank=True, default='https://github.com', max_length=500)),
                ('live_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frameworks', 'Frameworks & Libraries'), ('Databases', 'Databases'), ('Tools', 'Tools & Platforms')], max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=85, help_text='Percentage score between 1 and 100')),
                ('icon_name', models.CharField(blank=True, default='code', help_text='Icon identifier e.g. python, django, database', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. GitHub, LinkedIn, Email, Twitter', max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('icon_name', models.CharField(help_text='e.g. github, linkedin, mail, code', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
